server:
  ssl:
    enabled: true
    key-store-type: PKCS12
# The path to the keystore containing the certificate
    key-store: classpath:keystore/baeldung.p12
# The password used to generate the certificate
    key-store-password: password
# The alias mapped to the certificate
    key-alias: baeldung
spring:
  thymeleaf:
    cache: false

welcome:
  message: World
